name: tests

on: [push]


jobs:
  blackformat:
    runs-on: ubuntu-latest
    steps:
      # use black github action see https://black.readthedocs.io/en/stable/integrations/github_actions.html
      - uses: psf/black@stable
        with:
          options: "--check"

      - name: Check imports with pyflakes
        run: |
          pip install pyflakes
          pyflakes .
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: "python -m pip install flake8"
        name: Install Flake8
      - run: "python -m flake8 . --count --select=E9,F7,F82 --show-source"
        name: Flake8 Linting
